name: Generate Daily RSS Feed

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Generate RSS Feed
      run: |
        python generate_rss.py
        # Debug: Check if file was created
        ls -l christmas_countdown.xml
    
    - name: Commit and Push
      # Only run if file exists
      run: |
        if [ -f christmas_countdown.xml ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add christmas_countdown.xml
          git commit -m "Update Christmas countdown RSS"
          git push
        else
          echo "No RSS file generated"
          exit 1
        fi
